"""add language to posts

Revision ID: 703dd6279421
Revises: 9c282bd2316c
Create Date: 2023-09-04 16:10:47.481602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703dd6279421'
down_revision = '9c282bd2316c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
